
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: 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
          exclude_types: "release"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"