
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        run: |
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
          echo ${{ steps.semantic.outputs.new_release_version }}
        env:
          GITHUB_TOKEN: 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