on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "./"
            REMOTE_HOST: 141.94.71.85
            REMOTE_USER: aarrad
            TARGET: "/home/aarrad"


