
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release test
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: 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

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          rm ./src/main/resources/test.txt
          sudo echo ${{ steps.semantic.outputs.new_release_version }} >> ./src/main/resources/test.txt
          sudo cat ./src/main/resources/test.txt
          sudo ls ./src/main/resources
          git config --global user.email "arradabdellah1@gmail.com"
          git config --global user.name "Abdellaharrad"
          git add .
          git commit -m "docs:test"
          git push
        shell: bash
      - name: Execute Semantic Releas
        run: |
          npm i @semantic-release/apm-config
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
        env:
          GITHUB_TOKEN: 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




