on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H 141.94.71.85 >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz . aarrad@$141.94.71.85:/home/aarrad


