on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy with rsync
        run: |
          ssh aarrad@${{ secrets.SSH_HOST }} -p 1212
        shell: bash


