on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check
        uses: actions/checkout@v2
      - run: |
          npm i @semantic-release/changelog
      - name: Version Released
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true
      - run : |
          rm ./src/main/resources/version.txt
          echo ${{ steps.semantic.outputs.new_release_version }} >> ./src/main/resources/version.txt
          git config --global user.email "arradabdellah1@gmail.com"
          git config --global user.name "Abdellaharrad"
          git add .
          npx semantic-release
      - name: Create Release
        id: create_releas
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H 141.94.71.85 >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz . aarrad@$141.94.71.85:/home/aarrad


