on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy with rsync
        run: |
          ssh aarrad@141.94.71.85 -p 1212 -t "mkdir ~/.ssh"
        shell: sh


