on:
  push:
    branches:
    - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check
        uses: actions/checkout@v2
      - run : |
          git config --global user.email "arradabdellah1@gmail.com"
          git config --global user.name "Abdellaharrad"
          git add .
      - name: Version Released
        uses: cycjimmy/semantic-release-action@v3
      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: ./src/main/resources/version.txt
          FILE_DATA: ${{ steps.semantic.outputs.last_release_version }}

