on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy with rsync
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
        shell: sh


