on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy with rsync
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H 141.94.71.85 >> ~/.ssh/known_hosts
          ssh-keygen -R 141.94.71.85
          ssh -tt aarrad@141.94.71.85 -p 1212
        shell: bash


