
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check
      - uses: @semantic-release/changelog
      - uses: codfish/semantic-release-action@v1


      - name: Execute Semantic Release
        id: semantic
        run: |
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
          echo $RELEASE_VERSION
        env:
          GITHUB_TOKEN: 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
