on:
  push:
    branches:
    - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check
        uses: actions/checkout@v2
      - run : |
          rm ./src/main/resources/version.txt
          git config --global user.email "arradabdellah1@gmail.com"
          git config --global user.name "Abdellaharrad"
          git add .
      - name: Version Released
        uses: cycjimmy/semantic-release-action@v3

