on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy with rsync
        run: |
          mkdir aarrad@141.94.71.85:~/.ssh
          touch aarrad@141.94.71.85:~/.ssh/known_hosts
        shell: sh


