
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Abdellaharrad
          repo: versiontest

      - name: Execute Semantic Release
        id: semantic
        run: |
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
          echo ${{ steps.keydb.outputs.release }}
        env:
          GITHUB_TOKEN: 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
