on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check
        uses: actions/checkout@v2
      - run : |
          npm i @semantic-release/changelog
          npx semantic-release --dry-run >> version.txt
          git add .
      - name: Version Released
        uses: cycjimmy/semantic-release-action@v3
        id: semantic

