on:
  push:
    branches:
    - master
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: |
          ssh-keyscan -p 1212 -H 141.94.71.85  >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: |
          rsync -avz --rsh='ssh -p1212' ./ aarrad@141.94.71.85:/
        shell: bash


