
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute Semantic Release
        id: semantic
        run: |
          npm i @semantic-release/apm-config
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
        env:
          GITHUB_TOKEN: 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

      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: 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
          exclude_types: "release"
          view_top: 1
      - name: test
        run:  echo " id- ${steps.last_release.outputs.created_atd}"



