
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Semantic Release
        id: semantic
        run: |
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
          git log > C:\Abdellah\4IIR\StageOritech\testVersioning\Versioning\.github\workflows\test.txt
        env:
          GITHUB_TOKEN: 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
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "nodejs/node"
          type: "latest"
        run: echo ${{ steps.node_release.outputs.release }}