
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute Semantic Release
        id: semantic
        run: |
          npm i @semantic-release/apm-config
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
        env:
          GITHUB_TOKEN: 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
          NPM_TOKEN:  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

      - uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: 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
          NPM_TOKEN: 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

      - run: |
          echo $RELEASE_VERSION
          echo $RELEASE_MAJOR
          echo $RELEASE_MINOR
          echo $RELEASE_PATCH
        env:
          NEW_RELEASE_PUBLISHED: true
          GITHUB_TOKEN: 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
          NPM_TOKEN: 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




