
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        env:
          token: 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
          repository: "nodejs/node"
          type: "latest"

      - name: Execute Semantic Release
        id: semantic
        run: |
          npm i @semantic-release/changelog
          npm i @semantic-release/git
          npm i @semantic-release/github
          npx semantic-release
          echo ${{ steps.node_release.outputs.release }}
        env:
          GITHUB_TOKEN: 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
